### ISSUE TITLE
Car RIG Generation isn't working properly.

### ISSUE THREAD

**Issue by kprimme** [digicreatures/rigacar#126]
I'm getting this kind of output whenever I hit on generate CAR RIG. I tried Reinstalling Blender/rigacar Add-On several times but not getting the expected result from that either. BTW I'm using Blender 4.0.2 version now.
![Rig](https://github.com/digicreatures/rigacar/assets/97435711/6089a10c-20dd-470a-9d5f-431795533949)

This is the description of issue by Blender - 
**Python: Traceback (most recent call last):
  File "C:\Users\primm\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rigacar\car_rig.py", line 492, in generate
    self.generate_constraints_on_rig()
  File "C:\Users\primm\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rigacar\car_rig.py", line 774, in generate_constraints_on_rig
    self.generate_constraints_on_wheel_bones(name_suffix)
  File "C:\Users\primm\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rigacar\car_rig.py", line 1071, in generate_constraints_on_wheel_bones
    generate_constraint_on_wheel_brake_bone(wheel_brake, wheel)
  File "C:\Users\primm\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rigacar\car_rig.py", line 438, in generate_constraint_on_wheel_brake_bone
    wheel_brake_pose_bone.bone_group = wheel_pose_bone.bone_group
AttributeError: 'PoseBone' object has no attribute 'bone_group'**

**Comment by batonchick1** [comment]
You are creating a thread without reading the other threads below. In the previous thread, everything has already been corrected for the current version of blender. You need to use the corrected version.

**Comment by Alik-Blend** [comment]
Look! a very nice guy made a fix for 4.0, im yet to try it myself but hope this helps!
[https://www.youtube.com/watch?v=Fod9jM6C9nk](url)

**Comment by kprimme** [comment]
Thanks! that helped a lot now I'm getting perfect car rig. I tried it on various model now and satisfied with the result i got.

**Comment by Youngmerii** [comment]
I'm experiencing the same issue, I would really appreciate it if you could help with Blender 4.1."
