### ISSUE TITLE
Cannot use empties as wheels

### ISSUE THREAD

**Issue by spoonless** [digicreatures/rigacar#23]
When using empties for wheels, generation of the rig provides the following error:

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/david/.config/blender/2.83/scripts/addons/rigacar/car_rig.py", line 1376, in execute
    armature_generator.generate(context.scene)
  File "/home/david/.config/blender/2.83/scripts/addons/rigacar/car_rig.py", line 481, in generate
    self.generate_constraints_on_rig()
  File "/home/david/.config/blender/2.83/scripts/addons/rigacar/car_rig.py", line 760, in generate_constraints_on_rig
    self.generate_constraints_on_wheel_bones(name_suffix)
  File "/home/david/.config/blender/2.83/scripts/addons/rigacar/car_rig.py", line 1006, in generate_constraints_on_wheel_bones
    ground_sensor = pose.bones[name_suffix.name('GroundSensor')]
KeyError: 'bpy_prop_collection[key]: key "GroundSensor.Ft.L" not found'

location: <unknown location>:-1

**Comment by spoonless** [comment]
FIX: use a default bounding box for correction generation of the ground sensor (empty objects have 0 size bounding box)
