### ISSUE TITLE
Bake car steering, and wheels rotation not working in blender 3.1

### ISSUE THREAD

**Issue by c4thyxx** [digicreatures/rigacar#66]
comes up with this error: 
Python: Traceback (most recent call last):
  File "C:\Users\chase\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 163, in invoke
    self.frame_start, self.frame_end = action.frame_range
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 778, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: ANIM_OT_car_wheels_rotation_bake.frame_start expected an int type, not float

location: <unknown location>:-1

bpy.ops.anim.car_steering_bake()
Python: Traceback (most recent call last):
  File "C:\Users\chase\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 163, in invoke
    self.frame_start, self.frame_end = action.frame_range
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 778, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: ANIM_OT_car_steering_bake.frame_start expected an int type, not float

location: <unknown location>:-1

**Comment by c4thyxx** [comment]
Fixed, just needed to download version 7 :D
